# -*- coding: utf-8 -*-
"""Zero-Shot Document Classification BERT RoBERTa S-BERT .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PZ1pbLX03zJ3DdfA7yZLq62Aq5rEB_mI
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers
!pip install torch
!pip install scikit-learn
!pip install pandas
!pip install datasets
!pip install sentence-transformers
!pip install datasets

"""**Zero-Shot Document Classification using BERT**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
from transformers import BertTokenizer, BertModel
from sklearn.metrics import accuracy_score, classification_report
import torch

# Load and preprocess the BBC News dataset from Kaggle (replace with your file path)
data_path = "/content/drive/MyDrive/bbc-500docs.csv"
data = pd.read_csv(data_path)

# Split the data into train and test sets
train_data, test_data, train_labels, test_labels = train_test_split(data['text'], data['category'], test_size=0.4, random_state=42)

# Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Generate embeddings for train and test data
def generate_embeddings(texts):
    input_ids = tokenizer(texts, padding=True, truncation=True, return_tensors="pt", max_length=256)['input_ids']
    with torch.no_grad():
        embeddings = model(input_ids).pooler_output
    return embeddings

train_embeddings = generate_embeddings(train_data.tolist()).numpy()
test_embeddings = generate_embeddings(test_data.tolist()).numpy()

# Create a dictionary to store category embeddings
category_embeddings = {}

# Initialize category embeddings
categories = ['business', 'entertainment', 'politics', 'sport', 'tech']
for category in categories:
    category_embeddings[category] = []

# Iterate through train data to calculate embeddings for each category
for i, category in enumerate(train_labels):
    category_embeddings[category].append(train_embeddings[i])

# Calculate average embeddings for each category
for category, embeddings_list in category_embeddings.items():
    category_embeddings[category] = np.mean(embeddings_list, axis=0)

# Initiali ze lists to store predicted labels and true labels
predicted_labels = []
true_labels = []

# Calculate and store predicted labels based on maximum cosine similarity (zero-shot classification)
for test_emb, true_label in zip(test_embeddings, test_labels):
    max_similarity = -1
    most_similar_category = None
    for category, category_emb in category_embeddings.items():
        similarity = cosine_similarity([test_emb], [category_emb])[0][0]
        if similarity > max_similarity:
            max_similarity = similarity
            most_similar_category = category
    predicted_labels.append(most_similar_category)
    true_labels.append(true_label)

# Calculate accuracy and generate classification report
accuracy = accuracy_score(true_labels, predicted_labels)
classification_report_str = classification_report(true_labels, predicted_labels, target_names=categories)

print("Classification Results for BBC News (Zero-Shot Using Cosine Similarity with BERT)")
print(f"Accuracy: {accuracy}")
print("Classification Report:\n", classification_report_str)

# Iterate through test data, print text, and predicted category
for text, predicted_category in zip(test_data, predicted_labels):
    print("Text:")
    print(text)
    print("Predicted Category:")
    print(predicted_category)
    print("-------------")

print("Document Embeddings")
print(test_emb)

print("Category Embeddings")
print(category_emb)

# After calculating average embeddings for each category, you can print them
for category, category_emb in category_embeddings.items():
    print(f"Category: {category}")
    print("Embedding:")
    print(category_emb)
    print("------------------------------")

for category, category_emb in category_embeddings.items():
 # print("Embedding:")
  print(category_emb)

# Write the embeddings to a file
with open('test_embeddings.csv', 'w') as f:
    for embeddings in test_embeddings:
        f.write(' '.join(str(x) for x in embeddings) + '\n')
from google.colab import files

files.download('test_embeddings.csv')

"""**Zero-Shot Document Classification using RoBERTa**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
from transformers import RobertaTokenizer, RobertaModel
from sklearn.metrics import accuracy_score, classification_report
import torch

# Load and preprocess the BBC News dataset from Kaggle (replace with your file path)
data_path = "/content/drive/MyDrive/bbc-500docs.csv"  # Update this with the actual file path
data = pd.read_csv(data_path)

# Split the data into train and test sets
train_data, test_data, train_labels, test_labels = train_test_split(data['text'], data['category'], test_size=0.4, random_state=42)

# Load RoBERTa tokenizer and model
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
model = RobertaModel.from_pretrained('roberta-base')

# Generate embeddings for train and test data
def generate_embeddings(texts):
    input_ids = tokenizer(texts, padding=True, truncation=True, return_tensors="pt", max_length=256)['input_ids']
    with torch.no_grad():
        embeddings = model(input_ids).last_hidden_state.mean(dim=1)
    return embeddings

train_embeddings = generate_embeddings(train_data.tolist()).numpy()
test_embeddings = generate_embeddings(test_data.tolist()).numpy()

# Create a dictionary to store category embeddings
category_embeddings = {}

# Initialize category embeddings
categories = ['business', 'entertainment', 'politics', 'sport', 'tech']
for category in categories:
    category_embeddings[category] = []

# Iterate through train data to calculate embeddings for each category
for i, category in enumerate(train_labels):
    category_embeddings[category].append(train_embeddings[i])

# Calculate average embeddings for each category
for category, embeddings_list in category_embeddings.items():
    category_embeddings[category] = np.mean(embeddings_list, axis=0)

# Initialize lists to store predicted labels and true labels
predicted_labels = []
true_labels = []

# Calculate and store predicted labels based on maximum cosine similarity(zero-shot classification)
for test_emb, true_label in zip(test_embeddings, test_labels):
    max_similarity = -1
    most_similar_category = None
    for category, category_emb in category_embeddings.items():
        similarity = cosine_similarity([test_emb], [category_emb])[0][0]
        if similarity > max_similarity:
            max_similarity = similarity
            most_similar_category = category
    predicted_labels.append(most_similar_category)
    true_labels.append(true_label)

# Calculate accuracy and generate classification report
accuracy = accuracy_score(true_labels, predicted_labels)
classification_report_str = classification_report(true_labels, predicted_labels, target_names=categories)

print("Classification Results for BBC News (Zero-Shot Using Cosine Similarity with RoBERTa)")
print(f"Accuracy: {accuracy}")
print("Classification Report:\n", classification_report_str)

# Iterate through test data, print text, and predicted category
for text, predicted_category in zip(test_data, predicted_labels):
    print("Text:")
    print(text)
    print("Predicted Category:")
    print(predicted_category)
    print("-------------")

print("Document Embeddings")
print(test_emb)

print("Category Embeddings")
print(category_emb)

# Write the embeddings to a file
with open('test_embeddings.csv', 'w') as f:
    for embeddings in test_embeddings:
        f.write(' '.join(str(x) for x in embeddings) + '\n')
from google.colab import files

files.download('test_embeddings.csv')

# Write the embeddings to a file
with open('category_embeddings.csv', 'w') as f:
    for embeddings in category_embeddings:
        f.write(' '.join(str(x) for x in embeddings) + '\n')
from google.colab import files

files.download('category_embeddings.csv')

"""**Zero-Shot Document Classification using S-BERT**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
from sklearn.metrics import accuracy_score, classification_report

# Load and preprocess the BBC News dataset from Kaggle (replace with your file path)
data_path = "/content/drive/MyDrive/bbc-500docs.csv"
data = pd.read_csv(data_path)

# Split the data into train and test sets
train_data, test_data, train_labels, test_labels = train_test_split(data['text'], data['category'], test_size=0.4, random_state=42)

# Load a pre-trained SentenceTransformer model
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

# Generate embeddings for train and test data
train_embeddings = model.encode(train_data.tolist(), batch_size=64, show_progress_bar=True)
test_embeddings = model.encode(test_data.tolist(), batch_size=64, show_progress_bar=True)

# Create a dictionary to store category embeddings
category_embeddings = {}

# Initialize category embeddings
categories = ['business', 'entertainment', 'politics', 'sport', 'tech']
for category in categories:
    category_embeddings[category] = []

# Iterate through train data to calculate embeddings for each category
for i, category in enumerate(train_labels):
    category_embeddings[category].append(train_embeddings[i])

# Calculate average embeddings for each category
for category, embeddings_list in category_embeddings.items():
    category_embeddings[category] = np.mean(embeddings_list, axis=0)

# Initialize lists to store predicted labels and true labels
predicted_labels = []
true_labels = []

# Calculate and store predicted labels based on maximum cosine similarity(zero-shot classification)
for test_emb, true_label in zip(test_embeddings, test_labels):
    max_similarity = -1
    most_similar_category = None
    for category, category_emb in category_embeddings.items():
        similarity = cosine_similarity([test_emb], [category_emb])[0][0]
        if similarity > max_similarity:
            max_similarity = similarity
            most_similar_category = category
    predicted_labels.append(most_similar_category)
    true_labels.append(true_label)

# Calculate accuracy and generate classification report
accuracy = accuracy_score(true_labels, predicted_labels)
classification_report_str = classification_report(true_labels, predicted_labels, target_names=categories)

print("Classification Results for BBC News (Zero-Shot Using Cosine Similarity with SentenceTransformer)")
print(f"Accuracy: {accuracy}")
print("Classification Report:\n", classification_report_str)

# Iterate through test data, print text, and predicted category
for text, predicted_category in zip(test_data, predicted_labels):
    print("Text:")
    print(text)
    print("Predicted Category:")
    print(predicted_category)
    print("-------------")

print("Document Embeddings")
print(test_emb)

print("Category Embeddings")
print(category_emb)

# Write the embeddings to a file
with open('test_embeddings.csv', 'w') as f:
    for embeddings in test_embeddings:
        f.write(' '.join(str(x) for x in embeddings) + '\n')
from google.colab import files

files.download('test_embeddings.csv')

# Write the embeddings to a file
with open('category_embeddings.csv', 'w') as f:
    for embeddings in category_embeddings:
        f.write(' '.join(str(x) for x in embeddings) + '\n')
from google.colab import files

files.download('category_embeddings.csv')